### PR TITLE
Feature: Add heartbeat configure interface

### PR DESCRIPTION
**Pull request by littlepiggy03**
To be able to customize heartbeat message, interval ans target user.

Use it like this:
```javascript
// Customize heartbeat message
bot.setRollingMessageGetter(function () {
  // Return a heartbeat message
  // Typeof the return value should be "string", or the getter will be ignored
  return (new Date()).toJSON();
});
```
```javascript
// Customize heartbeat interval
bot.setRollingIntervalGetter(function () {
  // Return heartbeat interval in millisecond
  // Typeof the return value should be "number", or the getter will be ignored
  return 2 * 60 * 1000;
});
```
```javascript
// Customize heartbeats' target user
bot.setRollingTargetGetter(function () {
  // Return heartbeats' target user's username (such as "@xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")
  // Typeof the return value should be "string", or the getter will be ignored
  return bot.user.UserName || "filehelper";
});
```
Idea from nodeWechat/wechat4u#172 .

### CODE REVIEW

**Comment by spacelan** [comment]
nice work!

**Comment by spacelan** [comment]
@stonexer

**Comment by littlepiggy03** [comment]
Perhaps I should rename `Heartbeat` to `Polling` ?

**Comment by spacelan** [comment]
I think `Polling` would be better

**Comment by spacelan** [comment]
Could you kindly help me to update the README?

**Comment by littlepiggy03** [comment]
README updated.

**Pull request merged**
